import assert from "node:assert/strict";
import fs from "node:fs";
import test from "node:test";
import zlib from "node:zlib";

import {
  validateDashboardData,
  validatePreflopAggregateCache,
  validatePreflopHandEquityCache,
  validatePreflopHiddenVillainCache,
  validatePreflopPrimaryPriorCache,
  validatePriorWinShares,
} from "../dashboard/data_contracts.mjs";

const data = JSON.parse(fs.readFileSync(new URL("../dashboard/data/prior_portfolio.json", import.meta.url), "utf8"));
const preflopAggregateCache = JSON.parse(fs.readFileSync(new URL("../dashboard/data/preflop_aggregate_cache.json", import.meta.url), "utf8"));
const preflopPrimaryPriorCache = readJsonOrGzip("../essence_of_poker/data/preflop_primary_prior_cache.json");
const priorWinShares = JSON.parse(fs.readFileSync(new URL("../dashboard/data/prior_win_shares.json", import.meta.url), "utf8"));
const preflopHiddenVillainCache = JSON.parse(fs.readFileSync(new URL("../dashboard/data/preflop_hidden_villain_cache.json", import.meta.url), "utf8"));
const preflopHandEquityCache = JSON.parse(fs.readFileSync(new URL("../dashboard/data/preflop_hand_equity_cache.json", import.meta.url), "utf8"));

test("generated dashboard data satisfies the frontend contract", () => {
  assert.equal(validateDashboardData(data), data);
});

test("generated preflop aggregate cache satisfies the strict contract", () => {
  assert.equal(validatePreflopAggregateCache(preflopAggregateCache, { bucketCount: data.bucketCount, strictCounts: true }), preflopAggregateCache);
});

test("generated preflop primary prior cache satisfies the strict contract", () => {
  assert.equal(
    validatePreflopPrimaryPriorCache(preflopPrimaryPriorCache, { bucketCount: data.bucketCount, strictCounts: true }),
    preflopPrimaryPriorCache,
  );
});

test("generated prior win shares satisfy the strict contract", () => {
  assert.equal(validatePriorWinShares(priorWinShares), priorWinShares);
});

test("generated preflop hidden villain cache satisfies the strict contract", () => {
  assert.equal(
    validatePreflopHiddenVillainCache(preflopHiddenVillainCache, { bucketCount: data.bucketCount, strictCounts: true }),
    preflopHiddenVillainCache,
  );
});

test("generated preflop hand equity cache is explicitly approximate", () => {
  assert.equal(validatePreflopHandEquityCache(preflopHandEquityCache), preflopHandEquityCache);
});

test("dashboard data contract rejects malformed aggregate references", () => {
  const malformed = structuredClone(data);
  malformed.portfolios.hero.aggregates[0].assetCodes = ["missing"];

  assert.throws(() => validateDashboardData(malformed), /unknown asset missing/);
});

test("preflop aggregate cache contract rejects missing classes", () => {
  const malformed = { ...preflopAggregateCache, classes: {} };

  assert.throws(() => validatePreflopAggregateCache(malformed, { bucketCount: data.bucketCount }), /169 classes/);
});

test("preflop hand equity cache contract rejects false exactness", () => {
  const malformed = { ...preflopHandEquityCache, exact: true };

  assert.throws(() => validatePreflopHandEquityCache(malformed), /not generated by a proven exact equity engine/);
});

function readJsonOrGzip(relativePath) {
  const jsonUrl = new URL(relativePath, import.meta.url);
  if (fs.existsSync(jsonUrl)) {
    return JSON.parse(fs.readFileSync(jsonUrl, "utf8"));
  }
  const compressed = fs.readFileSync(new URL(`${relativePath}.gz`, import.meta.url));
  return JSON.parse(zlib.gunzipSync(compressed).toString("utf8"));
}
